repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.94.1
  hooks:
    - id: terraform_fmt
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
- repo: https://github.com/golangci/golangci-lint
  rev: v1.60.3
  hooks:
    - id: golangci-lint-config-verify
   # - id: golangci-lint
- repo: local
  hooks:
    - id: golangci-lint
      name: golangci-lint
      language: system
      require_serial: true
      pass_filenames: false
      types: [go]
      entry: golangci-lint run --new-from-rev HEAD --fix
    - id: gci
      name: gci
      language: golang
      entry: gci
        write
        --section standard
        --section default
        --section "prefix(github.com/nrkno/terraform-provider-ampp)"
      additional_dependencies:
        - github.com/daixiang0/gci@v0.13.5
# increase this number to bust github actions cache: 1
